FROM jenkins/jenkins:lts
USER root

# Install build tools and python
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    build-essential \
    make \
    gcc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER jenkins
