services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-swe6
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - /Users/hichamjazouli/.jenkins:/var/jenkins_home
      - .:/var/jenkins_home/workspace/SWE6-Test
    environment:
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    restart: always
