import re
import sys
import os
from datetime import datetime

# --- CONFIGURATION ---
TARGET_DIRS = ["src/app", "src/bsw", "src/main.c"]
REPORT_OUTPUT = "build/quality-report.html"

# --- RULES DEFINITION (MISRA-C:2012 & Architecture) ---
RULES = {
    "MISRA_15_1": {"id": "Rule 15.1", "desc": "Goto shall not be used", "pattern": r"\bgoto\b", "sev": "CRITICAL"},
    "MISRA_21_3": {"id": "Rule 21.3", "desc": "Dynamic memory banned (malloc/free)", "pattern": r"\b(malloc|free|calloc|realloc)\s*\(", "sev": "CRITICAL"},
    "MISRA_20_1": {"id": "Rule 20.1", "desc": "Include directives should only be preceded by preprocessor directives or comments", "pattern": r"^#include.*", "sev": "WARNING"},
    "ARCH_LAYER": {"id": "ARCH_01", "desc": "Layer Violation: ASW must not include BSW private headers", "pattern": r'#include\s*".*bsw_private.*"', "sev": "CRITICAL"},
    "CODING_01": {"id": "STYLE_01", "desc": "Magic numbers detected (use defined constants)", "pattern": r"=\s*\d{2,};", "sev": "ADVISORY"}
}

def generate_html_report(violations, stats):
    html = f"""
    <html>
    <head>
        <title>Quality Suite Report - {datetime.now().strftime('%Y-%m-%d %H:%M')}</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f7f6; color: #333; margin: 40px; }}
            .header {{ background: #2c3e50; color: white; padding: 20px; border-radius: 8px 8px 0 0; }}
            .stats-container {{ display: flex; gap: 20px; margin: 20px 0; }}
            .stat-card {{ background: white; padding: 15px 25px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); flex: 1; text-align: center; }}
            .stat-val {{ font-size: 24px; font-weight: bold; }}
            .CRITICAL {{ color: #e74c3c; }}
            .WARNING {{ color: #f39c12; }}
            .ADVISORY {{ color: #3498db; }}
            table {{ width: 100%; border-collapse: collapse; background: white; margin-top: 20px; border-radius: 8px; overflow: hidden; }}
            th, td {{ padding: 12px 15px; text-align: left; border-bottom: 1px solid #ddd; }}
            th {{ background-color: #ecf0f1; font-weight: bold; }}
            tr:hover {{ background-color: #f9f9f9; }}
            .badge {{ padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }}
            .badge-CRITICAL {{ background: #fadbd8; color: #e74c3c; }}
            .badge-WARNING {{ background: #fef5e7; color: #f39c12; }}
            .badge-ADVISORY {{ background: #ebf5fb; color: #3498db; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Suite Quality & Compliance Report</h1>
            <p>Project: SWE6-Test | Scope: Automotive ECU Firmware</p>
        </div>
        
        <div class="stats-container">
            <div class="stat-card">
                <div class="stat-val">{stats['total']}</div>
                <div>Total Findings</div>
            </div>
            <div class="stat-card">
                <div class="stat-val CRITICAL">{stats['critical']}</div>
                <div>Critical Violations</div>
            </div>
            <div class="stat-card">
                <div class="stat-val">{stats['files']}</div>
                <div>Files Analyzed</div>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Rule ID</th>
                    <th>Description</th>
                    <th>Severity</th>
                    <th>File</th>
                    <th>Line</th>
                    <th>Snippet</th>
                </tr>
            </thead>
            <tbody>
    """
    
    for v in violations:
        html += f"""
                <tr>
                    <td><b>{v['id']}</b></td>
                    <td>{v['desc']}</td>
                    <td><span class="badge badge-{v['sev']}">{v['sev']}</span></td>
                    <td>{v['file']}</td>
                    <td>{v['line']}</td>
                    <td><code>{v['snippet']}</code></td>
                </tr>
        """
    
    html += """
            </tbody>
        </table>
        <p style="margin-top: 20px; color: #95a5a6; font-size: 12px;">Report generated by Antigravity Quality Suite (Axivion Simulation)</p>
    </body>
    </html>
    """
    
    os.makedirs(os.path.dirname(REPORT_OUTPUT), exist_ok=True)
    with open(REPORT_OUTPUT, 'w') as f:
        f.write(html)

def analyze():
    violations = []
    stats = {"total": 0, "critical": 0, "files": 0}
    
    for target in TARGET_DIRS:
        files_to_check = []
        if os.path.isfile(target): files_to_check.append(target)
        else:
            for root, _, files in os.walk(target):
                for f in files:
                    if f.endswith(('.c', '.h')): files_to_check.append(os.path.join(root, f))
        
        for filepath in files_to_check:
            stats["files"] += 1
            with open(filepath, 'r') as f:
                for ln, content in enumerate(f.readlines(), 1):
                    # Clean line for analysis
                    clean_content = content.split("//")[0].split("/*")[0].strip()
                    if not clean_content: continue
                    
                    for key, rule in RULES.items():
                        if re.search(rule["pattern"], clean_content):
                            v = {
                                "id": rule["id"],
                                "desc": rule["desc"],
                                "sev": rule["sev"],
                                "file": filepath,
                                "line": ln,
                                "snippet": clean_content[:50] + "..." if len(clean_content) > 50 else clean_content
                            }
                            violations.append(v)
                            stats["total"] += 1
                            if v["sev"] == "CRITICAL": stats["critical"] += 1

    generate_html_report(violations, stats)
    
    print(f"✅ Analysis Complete. Findings: {stats['total']} ({stats['critical']} Critical)")
    print(f"📊 Dashboard generated: {REPORT_OUTPUT}")
    
    if stats['critical'] > 0:
        sys.exit(1)
    sys.exit(0)

if __name__ == "__main__":
    analyze()
